source "https://rubygems.org"

gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"

gem "base64", "~> 0.3.0"
gem "webrick", "~> 1.9"
gem "csv", "~> 3.3"
gem "bigdecimal"
gem "logger"
